### ISSUE TITLE
Create Initial Migration-ps

### ISSUE THREAD

**Issue by peterStaggs** [OrangeIguanas/bangazon-api#35]
Description: (What, Why) After creating our data models, we need to sync the database for the first time by creating a migration. 

Where:(file path) migration command executed in the terminal 

Pertinent Information: each class/model must be included in this migration

**Comment by abbyfleming** [comment]
Each time a class is modified, run migration. This will be an ongoing ticket and will happen simultaneously as we are working on different portions of the project.

**Comment by ZacharyCline** [comment]
Exactly! Thanks!
